### ISSUE TITLE
2.1 ID に対するアノテーション情報の取得機能の追加

### ISSUE THREAD

**Issue by sh-ikeda** [togoid/togoid-converter#189]
- ラベル表示機能を拡張し、ラベル以外の情報も取得し表示できるようにする
    - データの取得自体は、ラベルを取得するのに使っている grasp を同じように使用することで可能。
- このアノテーション情報を利用して、ID 変換結果の絞り込みを可能にする
    - 取得可能なアノテーション情報の種類ごとにフィルタリングのやり方が異なる
        - 有限個数の分類
            - 例: 遺伝子タイプ
            - チェックボックスで選択してフィルタリング
        - ラベルなど
            - 例: 生物種の場合、現行版で表示しているラベルは学名だが、一般名も知りたい
            - 文字列一致でフィルタリング
        - 数値情報
            - 例: 分子量
            - 数値範囲を指定してフィルタリング
- Results モーダルウィンドウに表示するべき内容が増えるので、わかりやすく使えるように適宜デザインの改修をする。

**Comment by sh-ikeda** [comment]
- テスト用サーバー
    - URL は議事録参照
- クエリ例
```graphql
query {
  ncbigene(id: ["1", "2", "52222"], type_of_gene: ["ncRNA", "protein-coding"]) {
    label
    id
    type_of_gene
  }
  uniprot(id: ["Q99999","P12345", "H0YBG3"], reviewed: ["true"]) {
    label
    short_name
    reviewed
  }
  chebi(id: ["15956", "16467"], mass_upper: 200, mass_lower: 100) {
    label
    mass
  }
}
```

- [togoid-config の dataset.yaml](https://github.com/togoid/togoid-config/blob/develop-2024/config/dataset.yaml) (develop-2024 ブランチ) に annotations という属性を追加し、データセットごとに使用可能なパラメータ名を記述した。
    - https://github.com/togoid/togoid-config/commit/eefd721aff8e43810ff46ad606e3fe2ee74e9711
    - https://github.com/togoid/togoid-config/commit/02d30e4ddc8ee69520576fe993c033ef8a983dbf


```yaml
ncbigene: 
 annotations:
    - variable: type_of_gene
      label: Type of gene
      items: ["protein-coding", "ncRNA", "pseudo", "rRNA", "tRNA", "scRNA", "snRNA", "snoRNA", "miscRNA", "biological-region", "unknown", "other"]
    - variable: gene_synonym
      label: Synonym
    - variable: full_name
      label: Full name
```
- `annotations` 属性下の各属性
    - `variable`
      graphQL クエリで取得するフィールド名に対応
    - `label`
       UI 上の表示名
    - `items`
      チェックボックスで選択させたい属性の選択肢
