### ISSUE TITLE
2.3 Results に表示される ID のリンク先を選択可能にする

### ISSUE THREAD

**Issue by sh-ikeda** [togoid/togoid-converter#191]
- 現在の TogoID では、Results モーダルウィンドウに表示される各データベースへのリンクは一通りになっている。データセットによっては、同一の ID を用いてリンクできる複数のデータベースが存在することがあるので、それらを選択できるようにする。
- dataset.yaml に、データセットごとに複数の URL プレフィックスを記述可能にし、プルダウンメニューの URL の選択肢としてそれらが追加されるイメージ。
![Image](https://github.com/user-attachments/assets/dae67fcf-b5ee-477a-b49c-133aaaab7022)
↑ この "URL" が複数になる。

**Comment by sh-ikeda** [comment]
[togoid-config の develop-2024 ブランチの dataset.yaml](https://github.com/togoid/togoid-config/blob/develop-2024/config/dataset.yaml)を更新し、選択肢を記述した。

変更前
```
affy_probeset:
  prefix: 'http://identifiers.org/affy.probeset/'
assembly_insdc:
  prefix: 'http://identifiers.org/insdc.gca/'
```

変更後
```
affy_probeset:
  prefix:
    - label: 'rdf'
      uri: 'http://identifiers.org/affy.probeset/'
      rdf: true
assembly_insdc:
  prefix:
    - label: 'identifiers.org'
      uri: 'http://identifiers.org/insdc.gca/'
      rdf: true
    - label: 'NCBI Genome Assembly'
      uri: 'https://www.ncbi.nlm.nih.gov/datasets/genome/'
    - label: 'ENA'
      uri: 'https://www.ebi.ac.uk/ena/data/view/'
```
従来は単一の文字列値を持っていた `prefix` 属性が、リストを持つようになった。
UI 上で、デフォルトのリンク先として使用するのはリストの最初の要素の `uri` 属性値。
上記 `assembly_insdc` の例のように、リストが複数の要素を持つときは、`label` 属性値を使って

URL (identifiers.org)
URL (NCBI Genome Assembly)
URL (ENA)

のように選択肢が並ぶ。それぞれを選択すると、該当する `uri` 属性値を使ったリンクが表示される。
上記 `affy_probeset` の例のように、リストが一個の要素しか持たないときは、ラベルを出す必要はなく、従来通りの表示でよい。

なお `rdf: true` は RDF 出力時に参照するだけなので、Web アプリ側では見る必要なし。
