### ISSUE TITLE
2.13 LABEL2ID の NCBI Gene のバックエンド変更

### ISSUE THREAD

**Issue by sh-ikeda** [togoid/togoid-converter#221]
現在の LABEL2ID はすべて PubDictionaries をバックエンドとしているが、辞書サイズの大きい NCBI Gene で動作が遅くなることがある。
NCBI Gene は完全一致しか認めないことにしているので、PubDictionaries に依存する必然性はない。そこで、NCBI Gene のみバックエンドを SPARQList に移行することにしたい。
UI の変更は必要なし。

### dataset.yaml
```yaml
    dictionaries:
      - label: NCBI Gene symbol
        dictionary: togoid_ncbigene_symbol
        preferred: true
      - label: Synonym
        dictionary: togoid_ncbigene_synonym
```
### API
https://pubdictionaries.org/find_ids.json?labels=ND1%7COCT4&dictionaries=togoid_ncbigene_symbol,togoid_ncbigene_synonym&tags=9606&threshold=1&verbose=true

出力 (一部のみ抜粋)
```json
{
  "ND1": [
    {
      "label": "ND1",
      "identifier": "4535",
      "dictionary": "togoid_ncbigene_symbol"
    }
  ],
  "OCT4": [
    {
      "label": "OCT4",
      "identifier": "5460",
      "dictionary": "togoid_ncbigene_synonym"
    }
  ]
}
```

入力文字列が、dataset.yaml の `preferred` で指定されるメインラベル以外とマッチした場合、そのエントリーのメインラベルを調べるために別の API を使っている。
https://pubdictionaries.org/find_terms.json?ids=5460&dictionaries=togoid_ncbigene_symbol

```json
{
  "5460": [{
    "label": "POU5F1",
    "dictionary": "togoid_ncbigene_symbol"
  }]
}
```

### dataset.yaml
```yaml
    sparqlist: label2id_ncbigene
    label_types:
      - label: NCBI Gene symbol
        label_type: symbol
        preferred: true
      - label: Synonym
        label_type: synonym
      - label: Locus Tag
        label_type: locus_tag
```
`sparqlist` 属性を持っているデータセット(当面は NCBI Gene のみ)は SPARQList を使う。
`label_types` 属性は従来の `dictionaries` 属性と全く同じ。
### API
仕様: https://dx.dbcls.jp/togoid/sparqlist/label2id_ncbigene
例: https://dx.dbcls.jp/togoid/sparqlist/api/label2id_ncbigene?labels=ND1%2COCT4&taxon=9606&label_types=symbol%2Csynonym%2Clocus_tag
- `label2id_ncbigene`
  `sparqlist` 属性の値。
- `labels`
  入力文字列。カンマ区切り。(PubDictionaries ではパイプ区切り)
- `taxon`
  生物種 ID。(PubDictionaries では `tags`)
- `label_types`
  ラベルタイプ。(PubDictionaries では `dictionaries`)

出力 (一部のみ抜粋)
```json
{
  "ND1": [
    {
      "label": "ND1",
      "identifier": "4535",
      "label_type": "symbol",
      "preferred": "ND1"
    }
  ],
  "OCT4": [
    {
      "label": "OCT4",
      "identifier": "642559",
      "label_type": "synonym",
      "preferred": "POU5F1P3"
    }
  ]
}
```
PubDictionaries の出力とほぼ同じ。`preferred` としてメインラベルが同時に取得できるので、従来のように二回問い合わせる必要はない。
